/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package tutorial;

import java.util.Hashtable;
import java.util.Vector;
import java.util.Enumeration;

public class tutorialConstants {

  public static final int INT32CONSTANT = 9853;

  public static final Hashtable MAPCONSTANT = new Hashtable();
  static {
    MAPCONSTANT.put("hello", "world");
    MAPCONSTANT.put("goodnight", "moon");
  }

}
